export const ERROR_CODES = {

  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  BUCKET_NOT_FOUND: 'BUCKET_NOT_FOUND',

  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',

  NO_FILE_UPLOADED: 'NO_FILE_UPLOADED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  SHARE_LINK_EXPIRED: 'SHARE_LINK_EXPIRED',
} as const;

export type ErrorCodeType = typeof ERROR_CODES[keyof typeof ERROR_CODES];